name: temporalenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit
  - matplotlib
  - tqdm
  - loguru
  - git
  - seaborn
  - scipy
  - brewer2mpl